"""
VIEWS - Vistas sin dependencia de base de datos
"""
from django.shortcuts import render


def inicio(request):
    """Página de inicio"""
    return render(request, 'inicio.html')


def plantas_completas(request):
    """Página con todas las plantas medicinales"""
    plantas = [
        {
            'nombre': 'Romero',
            'cientifico': 'Rosmarinus officinalis',
            'definicion': 'Arbusto leñoso perenne con hojas lineales y flores pequeñas de color azul, púrpura, rosa o blanco.',
            'descripcion': 'Planta originaria de la región mediterránea que crece entre 1 a 2 metros de altura. Sus hojas son aciculares, resistentes y aromáticas. Las flores emergen en racimos a lo largo del tallo durante primavera y verano. Se cultiva ampliamente en climas templados y precisa luz solar directa.',
            'uso_tradicional': 'Se hierve la rama entera en agua para preparar una infusión que estimula la concentración y mejora la circulación cerebral.',
            'importancia': 'Desde tiempos antiguos, es utilizado en rituales de purificación y como remedio natural contra el olvido y la confusión mental.',
        },
        {
            'nombre': 'Eucalipto',
            'cientifico': 'Eucalyptus globulus',
            'definicion': 'Árbol de gran altura con corteza lisa que se descama, hojas alargadas y flores blancas que emergen de cápsulas leñosas.',
            'descripcion': 'Árbol de rápido crecimiento originario de Australia que alcanza entre 40 a 60 metros de altura. Posee corteza lisa de color gris que se desprende en láminas. Sus hojas contienen glándulas oleosas que desprenden un aroma intenso y refrescante. Produce flores blancas y frutos leñosos.',
            'uso_tradicional': 'Se inhalan los vapores de sus hojas hervidas para aliviar la congestión nasal y la tos, o se prepara en té para fortalecer las vías respiratorias.',
            'importancia': 'Es una planta venerada en la medicina natural por su capacidad de limpiar y sanar el sistema respiratorio de generaciones.',
        },
        {
            'nombre': 'Cilantro',
            'cientifico': 'Coriandrum sativum',
            'definicion': 'Planta herbácea anual con tallos delgados, hojas compuestas finamente divididas y pequeñas flores blancas o rosadas.',
            'descripcion': 'Hierba anual de ciclo corto que crece hasta 50 cm de altura. Las hojas basales son ampliamente divididas mientras que las superiores son más finas y filiformes. Las flores forman pequeños racimos de color blanco o rosado pálido. Se cultiva en climas templados y requiere suelo bien drenado.',
            'uso_tradicional': 'Se consume fresco en ensaladas o se prepara en té para mejorar la digestión y ayudar al cuerpo a eliminar metales pesados y toxinas acumuladas.',
            'importancia': 'Tradicionalmente usado por la sabiduría popular para depurar el cuerpo y mantener la salud intestinal en las familias.',
        },
        {
            'nombre': 'Orégano',
            'cientifico': 'Origanum vulgare',
            'definicion': 'Planta herbácea perenne con tallos peludos, hojas ovales aromáticas y pequeñas flores púrpuras que crecen en racimos.',
            'descripcion': 'Hierba perenne que crece entre 30 a 60 cm de altura con tallos cubiertos de pelillos finos. Las hojas son ovales, aromáticas y desarrollan un color verde oscuro en madurez. Las flores púrpuras o rosadas se agrupan en inflorescencias densas. Prospera en suelos secos y bien drenados con exposición solar directa.',
            'uso_tradicional': 'Se prepara en infusión con sus hojas secas o frescas para fortalecer el sistema inmunológico y prevenir resfriados.',
            'importancia': 'Es considerado una hierba sagrada en las tradiciones curativas por su capacidad de proteger y fortalecer el cuerpo contra las enfermedades.',
        },
        {
            'nombre': 'Té Verde',
            'cientifico': 'Camellia sinensis',
            'definicion': 'Arbusto con hojas lanceoladas de color verde intenso, flores blancas delicadas y semillas que producen un aceite valioso.',
            'descripcion': 'Arbusto perenne que alcanza entre 1 a 3 metros en cultivo controlado. Posee hojas lanceoladas de color verde brillante que contienen compuestos polifenólicos. Las flores son blancas o ligeramente rosadas con estambres amarillos. Originario de zonas montañosas de Asia tropical, requiere altitud y clima húmedo.',
            'uso_tradicional': 'Se hierven sus hojas frescas en agua caliente para beber a lo largo del día, proporcionando energía sin provocar agitación.',
            'importancia': 'Ha sido valorizado durante miles de años en las culturas orientales como elixir de longevidad y sabiduría.',
        },
        {
            'nombre': 'Tila',
            'cientifico': 'Tilia cordata',
            'definicion': 'Árbol de gran tamaño con hojas cordiformes, flores amarillas perfumadas y frutos alados pequeños.',
            'descripcion': 'Árbol de hoja caduca que alcanza entre 15 a 30 metros de altura. Posee copa densa y hojas cordiformes asimétricas con margen dentado. Las flores amarillentas pequeñas brotan en racimos péndulos con una bráctea membranosa característica. El árbol vive entre 400 a 600 años en condiciones óptimas.',
            'uso_tradicional': 'Se prepara té con sus flores secas para inducir relajación muscular y mejorar la calidad del descanso nocturno de forma natural.',
            'importancia': 'Desde la antigüedad, las flores de tila son consideradas el remedio natural más efectivo para calmar la ansiedad y facilitar el sueño.',
        },
        {
            'nombre': 'Malva',
            'cientifico': 'Malva sylvestris',
            'definicion': 'Planta herbácea con tallos ramificados, hojas redondeadas lobuladas y flores de pétalos rosados con venas más oscuras.',
            'descripcion': 'Hierba bienal o perenne que crece entre 30 a 90 cm de altura. Posee hojas redondeadas profundamente lobuladas con peciolo largo. Las flores presentan pétalos rosados con venas de color más intenso y estambres soldados. Se cultiva en climas templados en suelos moderadamente fértiles.',
            'uso_tradicional': 'Se prepara una infusión con sus flores para hacer gárgaras y aliviar la irritación de garganta, o se bebe para calmar la inflamación intestinal.',
            'importancia': 'Ha sido usada por generaciones como remedio confiable para suavizar y sanar membranas inflamadas del sistema respiratorio y digestivo.',
        },
        {
            'nombre': 'Diente de León',
            'cientifico': 'Taraxacum officinale',
            'definicion': 'Planta herbácea perenne con hojas dentadas en roseta, flores amarillas solitarias y frutos redondos dispersos por el viento.',
            'descripcion': 'Hierba perenne cosmopolita que crece entre 10 a 50 cm de altura. Forma una roseta basal de hojas fuertemente dentadas con savia lechosa. Las flores amarillas solitarias se elevan en tallos huecos. Los frutos son esferas de semillas aladas que se dispersan por viento. Raíz pivotante profunda rica en nutrientes.',
            'uso_tradicional': 'Se prepara té con su raíz tostada y molida, o se comen sus hojas frescas en ensaladas para estimular la función hepática y la depuración.',
            'importancia': 'Reconocido en la medicina natural como uno de los depurativos más potentes para limpiar el hígado y la sangre.',
        },
        {
            'nombre': 'Albahaca',
            'cientifico': 'Ocimum basilicum',
            'definicion': 'Planta herbácea anual con tallos verdes, hojas ovaladas aromáticas y pequeñas flores blancas o rosadas.',
            'descripcion': 'Hierba anual tropical de rápido crecimiento que alcanza 30 a 60 cm de altura. Posee tallos verdes ramificados y hojas ovaladas de color verde brillante. Las flores pequeñas blancas o rosadas emergen en racimos. Requiere calor, luz solar y protección del frío extremo.',
            'uso_tradicional': 'Se utiliza fresca en alimentos o se prepara en té para mejorar la digestión, prevenir inflamación y mantener el equilibrio bacteriano interno.',
            'importancia': 'Considerada una hierba sagrada en muchas tradiciones por sus propiedades antibacterianas y su capacidad de armonizar el cuerpo.',
        },
        {
            'nombre': 'Jengibre',
            'cientifico': 'Zingiber officinale',
            'definicion': 'Planta rizomática con hojas lineales alargadas, flores amarillas con listas rojas y un rizoma aromático subterráneo.',
            'descripcion': 'Planta rizomática tropical que crece entre 60 a 90 cm. Posee hojas lineales alternas de color verde oscuro. Las flores están agrupadas en espigas densas de color amarillo con manchas rojas. El rizoma es grueso, nudoso y aromático con sabor picante característico.',
            'uso_tradicional': 'Se pela y se corta fresco para preparar té caliente o se añade a comidas para mejorar la digestión y combatir inflamaciones.',
            'importancia': 'Es un remedio ancestral venerado por su capacidad de calentar el cuerpo y fortalecer el sistema inmunológico en tiempos de enfermedad.',
        },
        {
            'nombre': 'Menta Piperita',
            'cientifico': 'Mentha piperita',
            'definicion': 'Planta herbácea perenne con tallos cuadrangulares, hojas dentadas aromáticas y pequeñas flores púrpuras.',
            'descripcion': 'Hierba perenne híbrida que crece entre 30 a 60 cm de altura. Posee tallos cuadrangulares ramificados con hojas dentadas de color verde oscuro. Las flores púrpuras pequeñas se disponen en espigas terminales. Contiene aceite esencial con alto contenido de mentol. Se reproduce por rizomas que se extienden horizontalmente.',
            'uso_tradicional': 'Se prepara té con sus hojas frescas o secas para aliviar problemas digestivos, dolores de cabeza por tensión y mejorar la concentración.',
            'importancia': 'Remedio ancestral transmitido por abuelos como protector de la salud respiratoria y bucal de las familias.',
        },
        {
            'nombre': 'Semillas de Lino',
            'cientifico': 'Linum usitatissimum',
            'definicion': 'Planta con tallos delgados, hojas lineales alternas, flores azules y semillas pequeñas de color dorado o marrón.',
            'descripcion': 'Planta herbácea anual que crece entre 20 a 90 cm de altura con tallos delgados sin ramificaciones. Posee hojas lineales alternas de color verde azulado. Las flores azul cielo tienen cinco pétalos con estambres desarrollados. Las semillas son pequeñas, planas y ovaladas de color marrón oscuro con aceite esencial.',
            'uso_tradicional': 'Se consumen molidas en agua o añadidas a alimentos para obtener omega-3, fibra y mejorar la salud cardiovascular e intestinal.',
            'importancia': 'Valoradas por generaciones como superalimento que proporciona nutrientes esenciales y protección cardiovascular.',
        },
        {
            'nombre': 'Tabaquillo',
            'cientifico': 'Polylepis',
            'definicion': 'Árbol de pequeña altura con corteza rojiza que se desprende en láminas finas, perteneciente a la familia Rosaceae.',
            'descripcion': 'Árbol altoandino que crece entre 5 a 8 metros de altura en zonas montañosas de Sudamérica. Posee corteza rojiza distintiva que se descama en láminas delgadas. Sus hojas son pequeñas y compuestas. Adaptado a suelos pobres y exposición a vientos fuertes en altitudes entre 4000 a 5000 metros.',
            'uso_tradicional': 'Se hierve su corteza en agua para preparar cocimientos que alivian afecciones respiratorias, tos y asma de forma natural.',
            'importancia': 'Usado desde tiempos prehispánicos en zonas altoandinas como remedio fundamental para mantener la salud respiratoria.',
        },
        {
            'nombre': 'Muérdago',
            'cientifico': 'Viscum album',
            'definicion': 'Planta semiparásita con tallos amarillentos, hojas pequeñas lanceoladas y bayas viscosas de color blanco nacarado.',
            'descripcion': 'Planta semiparásita hemiperenne que crece adherida a ramas de árboles hospedadores. Posee tallos dicótomos amarillentos con articulaciones. Las hojas son pequeñas, lanceoladas y perennes de color verde amarillento. Las bayas translúcidas contienen una pulpa viscosa blanca. Requiere árbol hospedador como manzano, álamo o roble.',
            'uso_tradicional': 'Se prepara una decocción con sus hojas para beber lentamente y regular naturalmente la presión arterial elevada.',
            'importancia': 'Desde la antigüedad, es reconocida como remedio natural para mantener la circulación sanguínea en equilibrio.',
        },
        {
            'nombre': 'Gordolobo',
            'cientifico': 'Verbascum thapsus',
            'definicion': 'Planta bienal de gran altura con hojas recubiertas de tricomas suaves, dándole aspecto blanquecino y aterciopelado.',
            'descripcion': 'Planta bienal de tallos rígidos que alcanza entre 1 a 2 metros de altura. En primer año forma roseta basal de hojas con tricomas densos. En segundo año produce tallo central erguido cubierto de hojas decrecientes. Las flores amarillas pequeñas se disponen en racimo denso apical. Los frutos son cápsulas globosas con muchas semillas diminutas.',
            'uso_tradicional': 'Sus flores se preparan en infusión para suavizar la garganta, expulsar flemas y calmar la irritación de los bronquios.',
            'importancia': 'Utilizado tradicionalmente como remedio natural más efectivo para todos los problemas respiratorios e inflamación de garganta.',
        },
        {
            'nombre': 'Lengua de Vaca',
            'cientifico': 'Rumex crispus',
            'definicion': 'Planta herbácea perenne con hojas basales de bordes ondulados y raíz larga y amarillenta rica en antraquinonas.',
            'descripcion': 'Hierba perenne que crece entre 60 a 120 cm de altura con raíz pivotante profunda de color amarillo. Las hojas basales son lanceoladas con márgenes ondulados característicos. Las flores verdosas pequeñas se agrupan en panículas. Florece entre junio y agosto. Los frutos son aquenios rodeados de alas membranosas.',
            'uso_tradicional': 'Se prepara té con su raíz seca para depurar el hígado, o se aplica en cataplasmas externas para limpiar impurezas de la piel.',
            'importancia': 'Considerada un potente depurativo ancestral para limpiar profundamente el cuerpo de toxinas acumuladas.',
        },
        {
            'nombre': 'Marrubio',
            'cientifico': 'Marrubium vulgare',
            'definicion': 'Planta de la familia Lamiaceae con tallos blanquecinos y flores pequeñas que crecen en anillos alrededor del tallo.',
            'descripcion': 'Hierba perenne de tallos blancos pubescentes que alcanza 30 a 60 cm de altura. Las hojas son opuestas, ovaladas y rugosas de color verde grisáceo. Las flores blancas pequeñas se agrupan en verticilos densos alrededor del tallo. Contiene glucósidos amargos característicos. Se desarrolla en suelos secos y calcáreos.',
            'uso_tradicional': 'Se prepara té con sus hojas para estimular la digestión, el apetito y facilitar la pérdida de peso de forma natural.',
            'importancia': 'Usado tradicionalmente para mejorar la función hepática y biliar, apoyando el metabolismo completo.',
        },
        {
            'nombre': 'Valeriana',
            'cientifico': 'Valeriana officinalis',
            'definicion': 'Planta con flores pequeñas blancas o rosadas agrupadas en racimos y raíz de olor fuerte y rígido.',
            'descripcion': 'Hierba perenne que crece entre 60 a 150 cm de altura con raíz pivotante corta y gruesa de aroma penetrante. El tallo es erguido, acanalado y hueco. Las hojas son pinnatipartidas opuestas con foliolos lanceolados. Las flores blancas o rosadas diminutas se agrupan en cimas corimbiformes terminales. Florece entre mayo y julio.',
            'uso_tradicional': 'Se hierve su raíz en agua para preparar té que induce relajación profunda y sueño reparador sin efectos secundarios.',
            'importancia': 'Ha sido la hierba sagrada durante siglos para calmar la ansiedad, los nervios y promover el sueño natural.',
        },
        {
            'nombre': 'Canela',
            'cientifico': 'Cinnamomum verum',
            'definicion': 'Árbol tropical con corteza aromática de color café rojizo que se seca y enrosca naturalmente en quills.',
            'descripcion': 'Árbol perennifolio que alcanza entre 10 a 15 metros de altura. Posee corteza lisa de color marrón grisáceo que cuando se pela internamente presenta el color café rojizo característico. Las hojas son opuestas, coriáceas con nervadura prominente. Las flores amarillentas aparecen en panículas. Los frutos son bayas negras ovaladas.',
            'uso_tradicional': 'Se hierve su corteza en agua para preparar té caliente que combate resfriados, mejora la digestión y calienta el cuerpo.',
            'importancia': 'Apreciada desde tiempos antiguos como especia medicinal que fortalece el sistema inmunológico y trae calidez.',
        },
        {
            'nombre': 'Manzanilla',
            'cientifico': 'Matricaria chamomilla',
            'definicion': 'Planta herbácea anual con flores blancas y centro amarillo, y aroma suave característico.',
            'descripcion': 'Hierba anual de tallos delgados erguidos que alcanza 15 a 60 cm de altura. Las hojas son bipinnatipartidas finamente divididas con olor aromático suave. Las flores son capítulos pequeños de 1 a 1.5 cm con flores periféricas blancas y disco central amarillo hueco. Se cultiva ampliamente en climas templados.',
            'uso_tradicional': 'Se prepara té con sus flores para aliviar dolores estomacales, cólicos, ansiedad y promover el descanso.',
            'importancia': 'Una de las plantas medicinales más usadas en los hogares por su seguridad y efectividad comprobada.',
        },
        {
            'nombre': 'Sábila',
            'cientifico': 'Aloe vera',
            'definicion': 'Planta suculenta con hojas gruesas verdes que contienen un gel transparente y pegajoso en su interior.',
            'descripcion': 'Suculenta perenne que forma rosetas basales compactas. Las hojas son carnosas, lanceoladas de 40 a 60 cm de largo con márgenes dentados característicos. La epidermis es verde grisácea. El interior contiene un parénquima mucilaginoso translúcido. Las flores son tubulares amarillas en racimos axilares. No resiste heladas.',
            'uso_tradicional': 'Se extrae el gel fresco de sus hojas para aplicar directamente en quemaduras, heridas y lesiones de piel.',
            'importancia': 'Valorada en cada hogar por su capacidad inmediata de cicatrizar y regenerar la piel de forma natural.',
        },
        {
            'nombre': 'Hierbabuena',
            'cientifico': 'Mentha spicata',
            'definicion': 'Planta aromática perenne de la familia Mentha con hojas verdes lanceoladas y aroma fresco de elegancia delicada.',
            'descripcion': 'Hierba perenne que crece entre 30 a 90 cm de altura con tallos cuadrangulares ramificados. Las hojas son lanceoladas con margen dentado de color verde brillante. Las flores púrpuras pálidas o blancas se disponen en espigas terminales. Se reproduce por rizomas subterráneos. Contiene aceite esencial sin mentol.',
            'uso_tradicional': 'Se hierve para preparar té que alivia la tos, la gripe y proporciona frescura digestiva inmediata.',
            'importancia': 'Transmitida de generación en generación como remedio natural para mantener la salud respiratoria.',
        },
        {
            'nombre': 'Margosa',
            'cientifico': 'Azadirachta indica',
            'definicion': 'Árbol perennifolio de rápido crecimiento con hojas de verde intenso, flores blancas fragantes y frutos amarillos.',
            'descripcion': 'Árbol tropical de crecimiento rápido que alcanza 15 a 20 metros de altura. Posee copa densa con hojas pinnaticompuestas de foliolos lanceolados de color verde oscuro. Las flores blancas pequeñas fragantes se agrupan en panículas axilares. Los frutos son drupas ovaladas amarillentas. Prospera en climas cálidos y tropicales.',
            'uso_tradicional': 'Se preparan infusiones con sus hojas para desinflamar, purificar la sangre y fortalecer las defensas.',
            'importancia': 'Conocida por la sabiduría popular como remedio antiinflamatorio poderoso que protege la salud integral.',
        },
        {
            'nombre': 'Epazote',
            'cientifico': 'Dysphania ambrosioides',
            'definicion': 'Planta herbácea de la familia Amaranthaceae originaria de América, perenne con aroma penetrante único.',
            'descripcion': 'Hierba perenne que crece entre 60 a 100 cm de altura con tallos ramificados verdes a rojos. Las hojas son alternas, lanceoladas con margen dentado y aroma penetrante característico. Las flores verdes diminutas se agrupan en espigas terminales. Los frutos son pixidios con semillas lenticulares. Se cultiva comúnmente en América Central y México.',
            'uso_tradicional': 'Se hierven sus hojas para preparar té que alivia cólicos, dolores estomacales y mejora la digestión.',
            'importancia': 'Remedio fundamental en la medicina tradicional mexicana para mantener la salud digestiva.',
        },
        {
            'nombre': 'Ruda',
            'cientifico': 'Ruta graveolens',
            'definicion': 'Subarbusto perenne de la familia Rutaceae con flores amarillas pequeñas que emiten aroma intenso y particular.',
            'descripcion': 'Subarbusto perenne que crece entre 60 a 100 cm de altura con tallos lignificados en base. Las hojas son bipinnatipartidas de color verde azulado. Las flores amarillas pequeñas nacen en cimas corimbiformes. Los frutos son cápsulas globosas con lóculos unidos. Emite aroma fuerte y característico.',
            'uso_tradicional': 'Se hierve en agua para beber como té que fortalece los vasos sanguíneos y mejora la circulación.',
            'importancia': 'Empleada desde tiempos remotos para fortalecer la circulación y proteger la salud cardiovascular.',
        },
        {
            'nombre': 'Menta',
            'cientifico': 'Mentha spp',
            'definicion': 'Género de plantas herbáceas, aromáticas y vivaces perteneciente a la familia Lamiaceae de aroma dulce.',
            'descripcion': 'Conjunto de plantas perennes que crecen entre 30 a 90 cm de altura con tallos cuadrangulares ramificados. Las hojas son opuestas, ovaladas con margen dentado y aroma aromático pronunciado. Las flores pequeñas púrpuras, blancas o rosadas se agrupan en espigas. Se reproducen por rizomas horizontales. Prefieren suelos húmedos y parcialmente sombreados.',
            'uso_tradicional': 'Se prepara té fresco para aliviar tos, gripe, mal aliento y mejorar la claridad mental de forma inmediata.',
            'importancia': 'Remedio ancestral transmitido por abuelos como protector de la salud respiratoria y bucal de las familias.',
        },
        {
            'nombre': 'Cúrcuma',
            'cientifico': 'Curcuma longa',
            'definicion': 'Planta rizomática con hojas grandes ovales, flores amarillas en espigas y rizoma subterráneo de color amarillo dorado.',
            'descripcion': 'Planta rizomática tropical que crece entre 60 a 90 cm de altura. Posee hojas grandes ovaladas de color verde oscuro con nervadura prominente. Las flores amarillas se agrupan en espigas terminales. El rizoma es cilíndrico, nudoso de color amarillo intenso con propiedades antiinflamatorias.',
            'uso_tradicional': 'Se muele el rizoma fresco o seco para añadir a alimentos calientes o preparar bebidas que reducen inflamación.',
            'importancia': 'Valorada en la medicina ayurvédica como la reina de las especias por sus propiedades desinflamatorias.',
        },
        {
            'nombre': 'Lavanda',
            'cientifico': 'Lavandula angustifolia',
            'definicion': 'Arbusto con hojas lineales grises, flores púrpuras pequeñas agrupadas en espigas aromáticas.',
            'descripcion': 'Arbusto perenne que crece entre 30 a 60 cm de altura con tallos leñosos en base. Las hojas son lineales, estrechas de color gris verde con aroma muy aromático. Las flores púrpuras pequeñas se disponen en espigas terminales densas. Prospera en suelos pobres, secos y bien drenados con luz solar directa.',
            'uso_tradicional': 'Se prepara té o se usan flores secas para inhalación que induce relajación profunda y mejora el sueño.',
            'importancia': 'Considerada ancestralmente como la flor sagrada del descanso, armonía emocional y paz interior.',
        },
    ]
    return render(request, 'plantas_completas.html', {'plantas': plantas})
